"""First-party Python client for the SkyPortal API."""

from skyportal_py import (
    acls,
    allocations,
    analysis,
    annotations,
    assignments,
    candidates,
    catalog_queries,
    classifications,
    comments,
    filters,
    followup_requests,
    galaxies,
    groups,
    instruments,
    localizations,
    mmadetectors,
    objs,
    observation_plans,
    observations,
    observing_runs,
    photometry,
    profile,
    roles,
    shifts,
    sources,
    spatial_catalogs,
    spectra,
    streams,
    tags,
    taxonomies,
    telescopes,
    users,
)
from skyportal_py._http import SkyPortalError, unwrap
from skyportal_py.client import SkyPortal, create_client

__all__ = [
    "SkyPortal",
    "SkyPortalError",
    "acls",
    "allocations",
    "analysis",
    "annotations",
    "assignments",
    "candidates",
    "catalog_queries",
    "classifications",
    "comments",
    "create_client",
    "filters",
    "followup_requests",
    "galaxies",
    "groups",
    "instruments",
    "localizations",
    "mmadetectors",
    "objs",
    "observation_plans",
    "observations",
    "observing_runs",
    "photometry",
    "profile",
    "roles",
    "shifts",
    "sources",
    "spatial_catalogs",
    "spectra",
    "streams",
    "tags",
    "taxonomies",
    "telescopes",
    "unwrap",
    "users",
]
